# Docker Compose override for integration testing scenarios
# Use: docker-compose -f docker-compose.yml -f docker-compose.test.yml up

version: '3.8'

services:
  redis:
    ports:
      - "47942:6379"  # Obscure host port to avoid collisions
    volumes:
      - ./monitoring/redis-low-memory.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  redis-exporter:
    ports:
      - "19121:9121"
  prometheus:
    ports:
      - "19090:9090"
  grafana:
    ports:
      - "13000:3000"
  node-exporter:
    ports:
      - "19100:9100"
    
  sre-agent:
    environment:
      - REDIS_URL=redis://redis:6379/0  # Internal container port stays 6379
      - PROMETHEUS_URL=http://prometheus:9090
      - GRAFANA_URL=http://grafana:3000
      - LOG_LEVEL=DEBUG
