server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    pipeline_stages:
      - docker: {}
    relabel_configs:
      # Ensure at least one label pair exists
      - action: replace
        target_label: job
        replacement: docker
      - action: replace
        target_label: host
        replacement: docker-desktop

      # Useful labels for filtering in Grafana
      - action: replace
        source_labels: ['__meta_docker_container_name']
        target_label: container
      # Override with compose service if present
      - action: replace
        source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: service
      - action: replace
        source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: compose_project
      # Fallback unique label if needed
      - action: replace
        source_labels: ['__meta_docker_container_id']
        regex: '(.+)'
        target_label: container_id

      # Read the Docker JSON log file for the container
      - source_labels: ['__meta_docker_container_id']
        target_label: __path__
        replacement: /var/lib/docker/containers/$1/$1-json.log


  - job_name: docker_all
    static_configs:
      - targets: [localhost]
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - docker: {}
