# Prometheus configuration for Redis SRE monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'redis-sre-monitor'

# Alerting configuration (would connect to Alertmanager in production)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "redis_rules.yml"
  # - "sre_rules.yml"

# Scrape configuration
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 15s

  # Redis metrics via redis_exporter
  - job_name: 'redis'
    static_configs:
      - targets:
          - 'redis-exporter:9121'           # redis-demo
          - 'redis-exporter-agent:9121'     # agent operational redis
          - 'redis-enterprise-exporter:9121' # optional, if DB exists on 12000
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  # System metrics via node_exporter
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: /metrics
    scrape_interval: 15s
    metric_relabel_configs:
      - source_labels: ['__name__']
        regex: 'node_(memory|vmstat|pressure_memory).*'
        action: drop



  # Inject Pushgateway demo series into the 'node' job labels via honor_labels
  # This allows the demo host ('demo-host') to appear as if reported by node_exporter
  # so the agent's host metrics queries (which prefer node job) will include them.
  - job_name: 'node-push'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']
    metrics_path: /metrics
    scrape_interval: 15s
    metric_relabel_configs:
      # Keep only metrics from the demo grouping (job="node", instance="demo-host")
      - source_labels: ['job','instance']
        regex: 'node;demo-host'
        action: keep


  # Redis Enterprise node metrics (local demo cluster)
  - job_name: 'redis-enterprise-nodes'
    scheme: https
    metrics_path: /metrics
    tls_config:
      insecure_skip_verify: true  # Local demo certs
    static_configs:
      - targets:
          - 'redis-enterprise-node1:9443'
          - 'redis-enterprise-node2:9443'
          - 'redis-enterprise-node3:9443'
    scrape_interval: 30s
    scrape_timeout: 10s

  # SRE Agent application metrics (if implemented)
  - job_name: 'sre-agent'
    static_configs:
      - targets: ['sre-agent:8000']
    metrics_path: /api/v1/metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: /metrics
    scrape_interval: 30s


  # Loki metrics for Log Volume and health
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
    metrics_path: /metrics
    scrape_interval: 30s

  # Pushgateway (for demo metrics pushed by examples/demo_scenarios.py)
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']
    metrics_path: /metrics
    scrape_interval: 15s

  # Promtail metrics (optional)
  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:9080']
    metrics_path: /metrics
    scrape_interval: 30s


  # SRE Worker metrics (Prometheus client in-process)
  - job_name: 'sre-worker'
    static_configs:
      - targets: ['sre-worker:9101']
    metrics_path: /
    scrape_interval: 30s
