{
 "title": "Redis Enterprise Nodes Logs",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "All Redis Enterprise nodes",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service=~\"redis-enterprise-node.*\"}"
    }
   ]
  },
  {
   "title": "redis-enterprise-node1 logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{service=\"redis-enterprise-node1\"}"
    }
   ]
  },
  {
   "title": "redis-enterprise-node2 logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{service=\"redis-enterprise-node2\"}"
    }
   ]
  },
  {
   "title": "redis-enterprise-node3 logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{service=\"redis-enterprise-node3\"}"
    }
   ]
  }
 ]
}