name: UI E2E (Playwright)

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start backend with docker-compose (test)
        run: |
          docker compose -f docker-compose.yml -f docker-compose.test.yml up -d --build redis-demo prometheus grafana sre-agent sre-worker

      - name: Wait for backend health
        run: |
          for i in {1..60}; do
            if curl -fsS http://localhost:8000/api/v1/health >/dev/null; then
              echo "Backend healthy"; exit 0; fi; sleep 2; done; echo "Backend not ready"; docker ps; docker logs $(docker ps -q --filter name=sre-agent) --tail=200; exit 1

      - name: Install UI deps
        working-directory: ui
        run: npm ci

      - name: Install Playwright browsers
        working-directory: ui
        run: npx playwright install --with-deps

      - name: Run Playwright tests (headless)
        working-directory: ui
        env:
          VITE_API_URL: http://localhost:8000
        run: npm run e2e

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ui/playwright-report
          if-no-files-found: ignore
